-- Supabase SQL for events table
create table if not exists events (
  id bigint generated by default as identity primary key,
  title text not null,
  date date not null,
  time text not null,
  phase text not null,
  location text not null,
  description text not null,
  poster text,
  attendees integer default 0,
  max_attendees integer default 50,
  ticketed boolean default false,
  updated_at timestamptz default now()
);

-- Index for fast lookup
create index if not exists idx_events_date on events(date);

-- Guest list for each event
create table if not exists event_guests (
  id bigint generated by default as identity primary key,
  event_id bigint references events(id) on delete cascade,
  name text not null,
  contact text,
  added_by text,
  created_at timestamptz default now()
);
create index if not exists idx_event_guests_event_id on event_guests(event_id);

-- Attendance details for each user/event
create table if not exists event_attendance (
  id bigint generated by default as identity primary key,
  event_id bigint references events(id) on delete cascade,
  user_id text not null,
  guest_id bigint references event_guests(id) on delete set null,
  name text not null,
  contact text,
  created_at timestamptz default now(),
  unique(event_id, user_id)
);
create index if not exists idx_event_attendance_event_id on event_attendance(event_id);
