-- Apollo Selene Mixtape Exchange schema
-- Run this in Supabase SQL Editor.

create extension if not exists "uuid-ossp";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  display_name text,
  city text,
  username text unique,
  bio text,
  plan_tier text not null default 'free' check (plan_tier in ('free', 'pro', 'label')),
  subscription_status text,
  stripe_customer_id text unique,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists username text unique;
alter table public.profiles add column if not exists bio text;
alter table public.profiles add column if not exists plan_tier text not null default 'free';
alter table public.profiles add column if not exists subscription_status text;
alter table public.profiles add column if not exists stripe_customer_id text unique;
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

create or replace function public.handle_new_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1))
  )
  on conflict (id) do update
    set email = excluded.email,
        display_name = coalesce(excluded.display_name, public.profiles.display_name);

  return new;
end;
$$;

create or replace function public.handle_profile_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_profile on auth.users;

create trigger on_auth_user_created_profile
after insert on auth.users
for each row execute procedure public.handle_new_user_profile();

drop trigger if exists on_profile_updated_at on public.profiles;

create trigger on_profile_updated_at
before update on public.profiles
for each row execute procedure public.handle_profile_updated_at();

create table if not exists public.mixtape_exchanges (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  sender_id uuid not null references auth.users(id) on delete cascade,
  receiver_id uuid not null references auth.users(id) on delete cascade,
  cassette_title text not null,
  set_style text,
  note text,
  sender_hub text,
  receiver_hub text,
  sender_lat double precision not null,
  sender_lng double precision not null,
  receiver_lat double precision not null,
  receiver_lng double precision not null,
  altitude double precision not null default 0.25,
  duration_seconds integer not null default 24,
  offset_seconds integer not null default 0,
  status text not null default 'pending' check (status in ('pending', 'in_flight', 'delivered', 'cancelled'))
);

create table if not exists public.mixtape_invites (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  sender_id uuid not null references auth.users(id) on delete cascade,
  invite_email text not null,
  status text not null default 'pending' check (status in ('pending', 'sent', 'accepted', 'failed'))
);

create index if not exists mixtape_exchanges_sender_idx on public.mixtape_exchanges(sender_id);
create index if not exists mixtape_exchanges_receiver_idx on public.mixtape_exchanges(receiver_id);
create index if not exists mixtape_exchanges_status_idx on public.mixtape_exchanges(status);
create index if not exists mixtape_invites_sender_idx on public.mixtape_invites(sender_id);
create index if not exists mixtape_invites_email_idx on public.mixtape_invites(invite_email);

alter table public.profiles enable row level security;
alter table public.mixtape_exchanges enable row level security;
alter table public.mixtape_invites enable row level security;

-- Profiles policies
drop policy if exists "profiles_select_authenticated" on public.profiles;

create policy "profiles_select_authenticated"
on public.profiles
for select
using (auth.role() = 'authenticated');

drop policy if exists "profiles_insert_self" on public.profiles;

create policy "profiles_insert_self"
on public.profiles
for insert
with check (auth.uid() = id);

drop policy if exists "profiles_update_self" on public.profiles;

create policy "profiles_update_self"
on public.profiles
for update
using (auth.uid() = id)
with check (auth.uid() = id);

-- Mixtape policies
drop policy if exists "mixtape_select_participants" on public.mixtape_exchanges;

create policy "mixtape_select_participants"
on public.mixtape_exchanges
for select
using (auth.uid() = sender_id or auth.uid() = receiver_id);

drop policy if exists "mixtape_insert_sender" on public.mixtape_exchanges;

create policy "mixtape_insert_sender"
on public.mixtape_exchanges
for insert
with check (auth.uid() = sender_id);

drop policy if exists "mixtape_update_participants" on public.mixtape_exchanges;

create policy "mixtape_update_participants"
on public.mixtape_exchanges
for update
using (auth.uid() = sender_id or auth.uid() = receiver_id)
with check (auth.uid() = sender_id or auth.uid() = receiver_id);

-- Invite policies
drop policy if exists "mixtape_invites_insert_sender" on public.mixtape_invites;

create policy "mixtape_invites_insert_sender"
on public.mixtape_invites
for insert
with check (auth.uid() = sender_id);

drop policy if exists "mixtape_invites_select_sender" on public.mixtape_invites;

create policy "mixtape_invites_select_sender"
on public.mixtape_invites
for select
using (auth.uid() = sender_id);

drop policy if exists "mixtape_invites_update_sender" on public.mixtape_invites;

create policy "mixtape_invites_update_sender"
on public.mixtape_invites
for update
using (auth.uid() = sender_id)
with check (auth.uid() = sender_id);

-- Optional: Earth page can point to this table directly with VITE_DELIVERY_TABLE=mixtape_exchanges.
